### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pyros2097**
Add some stuff discussed in issues

### CODE REVIEW

**Comment by EmergentBehavior** [comment]
I already have an existing PR for a lot of this, see: https://github.com/chris-ramon/graphql-go/pull/32.

**Comment by pyros2097** [comment]
Yeah I Know... But It was too late I had already done the work .. So I merged yours into mine. Plus I have an example. Anyway's lets see what happens...

**Comment by sogko** [comment]
Hi guys

I think it's fine to have 2 separate PRs, we'll merge in #32 first, followed by #34. That will give proper contribution credits for all involved 👍🏻

I want to give @chris-ramon a chance to review #32 first before merging it, from there we'll move on to this.

Thanks again guys!

**Comment by EmergentBehavior** [comment]
Cool beans -- the important part is we're ramping up contributions for the lib :)

**Comment by chris-ramon** [comment]
Thanks a lot @pyros2097!

I went ahead and merged #38 which contains similar updates if this PR, so could we just preserve from this PR the following two sections:

- Other Libraries Related
- Blog Posts that might be useful

Might I suggest for `Other Libraries Related` rename to `Third Party Libraries` and have a table like [this](https://github.com/codegangsta/negroni#third-party-middleware) so we could have some like the following:

## Third Party Libraries

Here is a current list of graphql compatible libraries. Feel free to put up a PR to add missing ones:


| Name | Author | Description |
| -----------|--------|-------------|
| [graphql-go-handler](https://github.com/sogko/graphql-go-handler) | [Hafiz Ismail](https://github.com/sogko) | Middleware to handle GraphQL queries through HTTP requests. |


For `Blog Posts that might be useful` rename to `Blog Posts`:

## Blog Posts

- [Learn Golang + GraphQL + Relay](https://medium.com/@sogko/learn-golang-graphql-relay-1-e59ea174a902)


For `Example` section I think we can handle in a new PR, since API had changed and not yet merge #20, and it should perhaps be very similar to the one on `graphql-js` - `Using GraphQL.js` section.

Please do share your thoughts on this, thanks! :+1:

**Comment by pyros2097** [comment]
Hi @chris-ramon,

I Think it all good since the API is changed. I'll just make another pull request for the other sections so that its even with your master.

**Pull request closed without merging**
